### ISSUE TITLE
Plotting examples on nbinteract.com render blank plots

### ISSUE THREAD

**Issue by RussTedrake** [SamLau95/nbinteract#114]
Sorry if this is a known issue -- I haven't seen it documented anywhere.  None of the plots in any of the examples I've seen on your website actually work.  (I've tried in both chrome and firefox)

from the first example on nbinteract.com, I see only:

![image](https://user-images.githubusercontent.com/6442292/74234592-30c3c680-4c9b-11ea-88b3-371823f9f9e2.png)

Examples that update textual / numerical output seem to work, but I've yet to find a working example with a plot.

**Comment by SamLau95** [comment]
Yikes, you're right. Taking a look. Thanks for the catch.

**Comment by RussTedrake** [comment]
Checking in -- since the issue is open I assume you know it's still broken?  I'd love to see this project usable again!

**Comment by SamLau95** [comment]
Oh weird, after I pushed 184d770 things seemed to work but now they aren't. Will take another look.

It looks like all bqplot-based plotting isn't working, but ipywidgets widgets seem okay.

**Comment by SamLau95** [comment]
Okay, looks like things are working at https://www.nbinteract.com/ . 

https://github.com/SamLau95/nbinteract/commit/2e63920a78136defedbae95aa3ab8f604938041f fixed this issue by pinning the `bqplot` version. Because it wasn't pinned before, Binder would default to the latest `bqplot` version which is incompatible with the current JS setup.
