### ISSUE TITLE
ModuleNotFoundError: No module named 'datascience'

### ISSUE THREAD

**Issue by pleabargain** [SamLau95/nbinteract#68]
I'm having trouble finding the package for 'datascience'
You can see the error here:
https://hub.mybinder.org/user/samlau95-nbinteract-gou7un05/notebooks/notebooks/matplotlib_bootstrap_example.ipynb

What is the fix? 
thank you

**Comment by SamLau95** [comment]
You'll have to start a Binder image using https://github.com/SamLau95/nbinteract-image, not nbinteract. 

Also, I can't see what problem you're having since Binder links will expire. Instead, you should describe the series of steps you took to reproduce the issue without using a specific Binder URL.
