### ISSUE TITLE
Dynamic tables

### ISSUE THREAD

**Issue by gustavengstrom** [SamLau95/nbinteract#98]
It would be nice to be able to display dynamic html content based on e.g. dropdown choice. I naively assumed the code below would work but it only displays the string values (doesn´t generate html). Anyone have an idea of how this could be achieved?

```
from IPython.display import display, HTML

def display_dynamic_table(number):
    return display(HTML(number))

interact(display_dynamic_table, number={'a': '<table><tr><td>test a<td/></tr></table>', 'b': '<table><tr><td>test b<td/></tr></table>'})
```

**Comment by SamLau95** [comment]
It looks like this code works on a HTML page converted with `nbinteract`:

![html](https://user-images.githubusercontent.com/2468904/46228639-8a7e5780-c317-11e8-88d7-34e7afa30944.gif)

I can tell it works because the HTML is generated when I open the browser Dev Tools, and because the raw HTML doesn't show up (e.g. I don't see any `<table>` output as text).

I believe the CSS in the converted notebook is a bit different from the CSS in Jupyter, which may cause some visual differences.

**Comment by gustavengstrom** [comment]
Weird it is working for me now as well... I restarted the server in between so maybe it was this that solved the problem. Thanks for a great package!
